# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'FoodPin' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'AVOSCloud','2.6.1'
  # Pods for FoodPin

  target 'FoodPinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodPinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
